# pandas puzzles

Inspired by [100 Numpy exercises](https://github.com/rougier/numpy-100), here are 100* short puzzles for testing your knowledge of [pandas'](http://pandas.pydata.org/) power.

Since pandas is a large library with many different specialist features and functions, these exercises focus mainly on the fundamentals of manipulating data (indexing, grouping, aggregating, cleaning), making use of the core DataFrame and Series objects.

Many of the exercises here are straight-forward in that the solutions require no more than a few lines of code (in pandas or NumPy... don't go using pure Python or Cython!). Choosing the right methods and following best practices is the underlying goal.

The exercises are loosely divided in sections. Each section has a difficulty rating; these ratings are subjective, of course, but should be a seen as a rough guide as to how inventive the required solution is.

If you're just starting out with pandas and you are looking for some other resources, the official documentation  is very extensive. In particular, some good places get a broader overview of pandas are...

- [10 minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)
- [pandas basics](http://pandas.pydata.org/pandas-docs/stable/basics.html)
- [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html)
- [cookbook and idioms](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy*

**1.** Import pandas under the alias `pd`.

In [169]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [8]:
print(pd. __version__)

2.2.2


**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [10]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.7.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 24.3.0
Version               : Darwin Kernel Version 24.3.0: Thu Jan  2 20:23:36 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T8112
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 75.1.0
pip                   : 24.2
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : 7.3.7
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.2.1
html5lib             

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [207]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame (data=data, index=labels)

**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [14]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**6.** Return the first 3 rows of the DataFrame `df`.

In [16]:
print(df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no


**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [18]:
print(df.loc[:,["animal","age"]])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0


In [62]:
print(df.iloc[:, 0:2])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0


**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [73]:
print(df.loc[
      ["c", "d", "h"],
       ["animal", "age"]
      ])

  animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN


**9.** Select only the rows where the number of visits is greater than 3.

In [92]:
print(df["visits"]>3)

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i    False
j    False
Name: visits, dtype: bool


In [258]:
print(df[(df["visits"]>3)])

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []


**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [120]:
print(df[df["age"].isna()])

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [132]:
print(df[(df["animal"] == "cat") & (df["age"] < 3)])

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


**12.** Select the rows the age is between 2 and 4 (inclusive).

In [134]:
print(df[(df["age"] != 2) & (df["age"] != 3) & (df["age"] != 4)])

  animal  age  visits priority
a    cat  2.5       1      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no


In [144]:
# Assistant
# Filter dataframe to exclude ages 2, 3, and 4 using the ~isin() method
# More concise and readable than multiple conditions
# isin() checks if values are in the given list [2,3,4]
# ~ operator inverts the boolean mask (True becomes False and vice versa)
# So ~isin() means "is not in the list"
print(df[~df["age"].isin([2, 3, 4])])

  animal  age  visits priority
a    cat  2.5       1      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no


**13.** Change the age in row 'f' to 1.5.

In [156]:
df.loc["f","age"] = 1.5
print(df.loc["f",:])

animal      cat
age         1.5
visits      3.0
priority     no
Name: f, dtype: object


**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [164]:
print(df.sum()["visits"])

19.5


**15.** Calculate the mean age for each different animal in `df`.

In [174]:
print(df["animal"].unique())

['cat' 'snake' 'dog']


In [266]:
print("Mean age for a cat: " + str(df[df["animal"] == "cat"]["age"].mean()))
print("Mean age for a dog: " + str(df[df["animal"] == "dog"]["age"].mean()))
print("Mean age for a snake: " + str(df[df["animal"] == "snake"]["age"].mean()))

Mean age for a cat: 2.3333333333333335
Mean age for a dog: 5.0
Mean age for a snake: 2.5


**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [64]:
df.loc['k'] = ["pig", 5, 5, "no"]
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    pig  5.0       5       no


In [66]:
df.drop(df[df["animal"] == "pig"].index, inplace=True)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**17.** Count the number of each type of animal in `df`.

In [68]:
print("no. of cat: " + str(len(df[df['animal'] == 'cat'])))
print("no. of dog: " + str(len(df[df['animal'] == 'dog'])))
print("no. of snake: " + str(len(df[df['animal'] == 'snake'])))

no. of cat: 4
no. of dog: 4
no. of snake: 2


**18.** Sort `df` first by the values in the 'age' in *descending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [84]:
df.sort_values(by=['age', 'visits'], ascending= [False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [92]:
df.replace({'priority': {'no': False, 'yes': True}})

/var/folders/sp/g7sxk3ks3l53htnh17p_16sw0000gn/T/ipykernel_80467/2913254902.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'priority': {'no': False, 'yes': True}})


animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [94]:
df.replace('snake', 'python')

animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  2.0       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [104]:
df.pivot_table(values="age", index="animal", columns="visits", aggfunc="mean")

visits    1    2    3
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
snake   4.5  0.5  NaN

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [17]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df_filtered = df[df['A'] != df['A'].shift()]
print(df_filtered)

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7


**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [27]:
np.random.seed(10)
df = pd.DataFrame(np.random.random(size=(5, 3)))
print(df)

          0         1         2
0  0.771321  0.020752  0.633648
1  0.748804  0.498507  0.224797
2  0.198063  0.760531  0.169111
3  0.088340  0.685360  0.953393
4  0.003948  0.512192  0.812621


In [32]:
df_centered = df.sub(df.mean(axis=1).to_frame().values, axis=0)
print(df_centered)

          0         1         2
0  0.296080 -0.454488  0.158408
1  0.258101  0.007804 -0.265906
2 -0.177839  0.384629 -0.206791
3 -0.487358  0.109662  0.377696
4 -0.438972  0.069272  0.369700


In [ ]:
# Explanation:
# df.mean(axis=1): Computes the mean for each row.
# .to_frame().values: Converts the row means into a 2D array for proper broadcasting.
# df.sub(..., axis=0): Subtracts the row-wise mean from each element.

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [38]:
np.random.seed(10)
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
print(df)

          a         b         c         d         e         f         g  \
0  0.771321  0.020752  0.633648  0.748804  0.498507  0.224797  0.198063   
1  0.685360  0.953393  0.003948  0.512192  0.812621  0.612526  0.721755   
2  0.542544  0.142170  0.373341  0.674134  0.441833  0.434014  0.617767   
3  0.805223  0.521647  0.908649  0.319236  0.090459  0.300700  0.113984   
4  0.547586  0.819287  0.198948  0.856850  0.351653  0.754648  0.295962   

          h         i         j  
0  0.760531  0.169111  0.088340  
1  0.291876  0.917774  0.714576  
2  0.513138  0.650397  0.601039  
3  0.828681  0.046896  0.626287  
4  0.883936  0.325512  0.165016  


In [61]:
df.sum().idxmin(axis=0)

'g'

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [67]:
np.random.seed(10)
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
print(df)

   0  1  2
0  1  1  0
1  1  0  1
2  1  0  1
3  1  0  1
4  1  0  0
5  1  0  0
6  0  0  0
7  1  0  0
8  1  1  0
9  0  1  0


In [84]:
df.drop_duplicates().shape[0]

5

The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values.

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [88]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

def find_third_nan(row):
    nan_indices = row[row.isna()].index  
    return nan_indices[2] 

df['third_nan_column'] = df.apply(find_third_nan, axis=1)

print(df[['third_nan_column']])

  third_nan_column
0                e
1                c
2                d
3                h
4                d


**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals':

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [157]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

def top_3_sum(group):
    return group.nlargest(3, 'vals').sum()

result = df.groupby('grps').apply(top_3_sum, include_groups=False)

print(result)

      vals
grps      
a      409
b      156
c      345


**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive).

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [165]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
bins = pd.cut(df['A'], bins=range(0, 101, 10))
result = df.groupby(bins, observed=True)['B'].sum()
print(result)

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64


In [ ]:
# Explanation:
# pd.cut(df['A'], bins=range(0, 101, 10)): This creates intervals for the values in 'A'. The bins=range(0, 101, 10) creates intervals like (0, 10], (10, 20], ..., (90, 100].
# df.groupby(bins)['B'].sum(): Groups the DataFrame by these intervals and calculates the sum of column 'B' for each group.

## DataFrames: harder problems

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [293]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

# Initialize an empty list to store the values of 'Y'
y_values = []
counter = 0

# Iterate through the 'X' column
for x in df['X']:
    if x == 0:
        counter = 0
    else:
        counter += 1
    y_values.append(counter)

# Assign the list as a new column 'Y'
df['Y'] = y_values

print(df)

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2


**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data.

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [500]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
print(df)

    0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31


In [512]:
largest_values = df.stack().nlargest(3).index
print(largest_values)

MultiIndex([(5, 2),
            (4, 6),
            (7, 5)],
           )


In [520]:
#df.stack() is a method in pandas that "compresses" the columns of a DataFrame into a single column, essentially reshaping the DataFrame from a wide format to a long format. It stacks the columns into a Series, where the index is a MultiIndex consisting of the row and column labels of the original DataFrame.

**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [534]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

group_means = df[df['vals'] > 0].groupby('grps')['vals'].mean()
df['patched_vals'] = df.apply(lambda row: group_means[row['grps']] if row['vals'] < 0 else row['vals'], axis=1)
print(df)

    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6


**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [546]:
df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})

df['rolling_mean'] = df.groupby('group')['value'].rolling(window=3, min_periods=1).mean().reset_index(level=0, drop=True)
print(df['rolling_mean'])

0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
Name: rolling_mean, dtype: float64


In [ ]:
#Explanation:
#groupby('group'): This groups the DataFrame by the group column.
#rolling(window=3, min_periods=1): This applies a rolling window of size 3 and ensures that at least one non-null value is required to compute the mean (min_periods=1).
#.mean(): This computes the mean of each rolling window while ignoring NaN values.
#reset_index(level=0, drop=True): This resets the index after the rolling operation to avoid introducing a multi-level index.

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.


**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [246]:
business_days = pd.date_range(start = '01/01/2015', end = '31/12/2015')
random_numbers = np.random.randint(low = 0, high = 100, size = len(business_days))
s = pd.Series(data = random_numbers, index = business_days)
print(s)


2015-01-01    16
2015-01-02    52
2015-01-03    28
2015-01-04    69
2015-01-05    73
              ..
2015-12-27    56
2015-12-28    46
2015-12-29    30
2015-12-30    54
2015-12-31     4
Freq: D, Length: 365, dtype: int64


**34.** Find the sum of the values in `s` for every Wednesday.

In [248]:
s[s.index.weekday == 2].sum()

2299

**35.** For each calendar month in `s`, find the mean of values.

In [254]:
import calendar
monthly_mean = s.groupby(s.index.month).mean()
monthly_mean.index = monthly_mean.index.map(lambda x: calendar.month_name[x])
print(monthly_mean)

January      49.838710
February     49.714286
March        56.741935
April        47.266667
May          53.322581
June         55.366667
July         47.419355
August       50.645161
September    45.900000
October      48.548387
November     56.600000
December     42.709677
dtype: float64


In [260]:
# A lambda function in Python is a small, anonymous function that can have any number of arguments but only one expression. It is often used for short, simple functions that are not meant to be reused elsewhere.
# lambda x: calendar.month_name[x] is a lambda function that takes a single argument x (the month number) and returns the corresponding month name using calendar.month_name[x].
# In this case, you only need a short, one-time function to map numbers (1 to 12) to month names. Using a lambda lets you do this concisely without needing to define a separate function.

**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [274]:
highest_dates = s.groupby(((s.index.month - 1) // 4) + 1).idxmax()
highest_values = s.groupby(((s.index.month - 1) // 4) + 1).max()
result = pd.DataFrame({
    'Highest Date': highest_dates,
    'Highest Value': highest_values
})
print(result)

  Highest Date  Highest Value
1   2015-01-21             97
2   2015-05-22             99
3   2015-09-08             99


**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [285]:
dates = pd.date_range('2015-01-01', '2016-12-31', freq='MS')

def third_thursday(date):
    first_day = date
    weekday_of_first = first_day.weekday() 
    
    days_to_first_thursday = (3 - weekday_of_first) % 7
    
    first_thursday = first_day + pd.Timedelta(days=days_to_first_thursday)
    
    third_thursday = first_thursday + pd.Timedelta(weeks=2)
    
    return third_thursday

third_thursdays = dates.map(third_thursday)

print(third_thursdays)

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq=None)


## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)


**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [428]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

df.iloc[[1],[1]] = 10055
df.iloc[[3],[1]] = 10075
df['FlightNumber'] = df['FlightNumber'].astype('int')
print(df)

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"


**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame.

In [418]:
temp = df[['From_To']].copy()
temp[['From', 'To']] = temp.pop('From_To').str.split('_', expand=True)
print(temp)

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


In [340]:
#df.pop returns item and drops from frame.

**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [420]:
temp[['From', 'To']] = temp[['From', 'To']].apply(lambda x: x.str.capitalize())
print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


In [359]:
#Understanding apply()
#.apply(func, axis=0) applies the function column-wise (default behavior).
#lambda x: x.str.capitalize() defines an anonymous function (lambda x), where x represents each column separately.
#.str.capitalize() converts the first letter to uppercase while keeping the rest lowercase for every string value in each column.

**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [430]:
df = df.drop(columns=['From_To'])
df.insert(0, 'From', temp['From']) 
df.insert(1, 'To', temp['To'])
print(df)

       From         To  FlightNumber  RecentDelays              Airline
0    London      Paris         10045      [23, 47]               KLM(!)
1    Madrid      Milan         10055            []    <Air France> (12)
2    London  Stockholm         10065  [24, 43, 87]  (British Airways. )
3  Budapest      Paris         10075          [13]       12. Air France
4  Brussels     London         10085      [67, 32]          "Swiss Air"


**42**. In the **Airline** column, you can see some extra punctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [452]:
df['Airline'] = df['Airline'].str.replace(r'[^a-zA-Z\s]', '', regex=True)
print(df['Airline'])

0                 KLM
1         Air France 
2    British Airways 
3          Air France
4           Swiss Air
Name: Airline, dtype: object


In [459]:
#[^a-zA-Z\s] → Keeps only letters (a-z, A-Z) and spaces (\s).
#regex=True → Ensures Pandas treats it as a regex operation.
#Regex is short for Regular Expression, it's a sequence of characters that forms a search pattern. It’s used for matching text in strings, allowing for complex string search, replacement, and extraction tasks.
#Key Components of Regex:
#Literals: Characters that match themselves (e.g., a matches the letter a).
#Meta-characters: Special characters that help define more complex patterns (e.g., \d for digits, \w for word characters, . for any character).
#Quantifiers: Define how many times a pattern should repeat (e.g., * means "zero or more," + means "one or more").
#Character classes: Grouping of characters to match (e.g., [a-z] matches any lowercase letter).

**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [482]:
delays = pd.DataFrame(df['RecentDelays'].to_list(), columns=['delay_1','delay_2','delay_3'])
print (delays)

   delay_1  delay_2  delay_3
0     23.0     47.0      NaN
1      NaN      NaN      NaN
2     24.0     43.0     87.0
3     13.0      NaN      NaN
4     67.0     32.0      NaN


In [488]:
df = df.drop(columns=['RecentDelays'])
df.insert(3, 'delay_1', delays['delay_1']) 
df.insert(4, 'delay_2', delays['delay_2'])
df.insert(5, 'delay_3', delays['delay_3'])       
print(df)

       From         To  FlightNumber  delay_1  delay_2  delay_3  \
0    London      Paris         10045     23.0     47.0      NaN   
1    Madrid      Milan         10055      NaN      NaN      NaN   
2    London  Stockholm         10065     24.0     43.0     87.0   
3  Budapest      Paris         10075     13.0      NaN      NaN   
4  Brussels     London         10085     67.0     32.0      NaN   

            Airline  
0               KLM  
1       Air France   
2  British Airways   
3        Air France  
4         Swiss Air  


In [493]:
df = df[['FlightNumber', 'Airline', 'From', 'To', 'delay_1', 'delay_2', 'delay_3']]
print(df)

   FlightNumber           Airline      From         To  delay_1  delay_2  \
0         10045               KLM    London      Paris     23.0     47.0   
1         10055       Air France     Madrid      Milan      NaN      NaN   
2         10065  British Airways     London  Stockholm     24.0     43.0   
3         10075        Air France  Budapest      Paris     13.0      NaN   
4         10085         Swiss Air  Brussels     London     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN  


The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```